import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { GradeLevel } from '../../enums';

/** One quiz-attempt summary row inside the report */
export class QuizAttemptSummaryDto {
  @ApiProperty({ example: '2025-01-06T08:00:00.000Z' })
  completedAt!: Date;

  @ApiProperty({ description: 'Score 0-100', example: 85 })
  score!: number;

  @ApiProperty({ example: 10 })
  totalQuestions!: number;

  @ApiProperty({ example: 8 })
  correctAnswers!: number;
}

/** Weekly or monthly progress report for one student */
export class StudentProgressReportDto {
  // ── Identity ──────────────────────────────────────────────────────────────
  @ApiProperty({
    description: 'Student profile ID',
    example: '507f1f77bcf86cd799439012',
  })
  studentProfileId!: string;

  @ApiProperty({ example: 'Nguyễn Văn A' })
  fullName!: string;

  @ApiPropertyOptional({
    enum: GradeLevel,
    enumName: 'GradeLevel',
    nullable: true,
  })
  gradeLevel?: GradeLevel | null;

  @ApiPropertyOptional({ nullable: true })
  schoolName?: string | null;

  // ── Cumulative stats (all-time) ───────────────────────────────────────────
  @ApiProperty({
    description: 'Total XP accumulated (all time)',
    example: 1240,
  })
  xpTotal!: number;

  @ApiProperty({ description: 'Current daily login streak', example: 7 })
  currentStreak!: number;

  @ApiProperty({ description: 'Diamond balance', example: 320 })
  diamondBalance!: number;

  // ── Period stats ──────────────────────────────────────────────────────────
  @ApiProperty({
    description: 'Report period start (ISO string)',
    example: '2025-01-01T00:00:00.000Z',
  })
  periodStart!: Date;

  @ApiProperty({
    description: 'Report period end (ISO string)',
    example: '2025-01-07T23:59:59.999Z',
  })
  periodEnd!: Date;

  @ApiProperty({ description: 'Lessons started during the period', example: 5 })
  lessonsStarted!: number;

  @ApiProperty({
    description: 'Lessons fully completed during the period',
    example: 3,
  })
  lessonsCompleted!: number;

  @ApiProperty({
    description: 'Total watch time in minutes during the period',
    example: 74,
  })
  totalWatchMinutes!: number;

  @ApiProperty({
    description: 'Number of quizzes attempted during the period',
    example: 4,
  })
  quizzesAttempted!: number;

  @ApiProperty({
    description:
      'Average quiz score across attempts in the period (0-100, null if none)',
    example: 78.5,
    nullable: true,
  })
  avgQuizScore!: number | null;

  @ApiProperty({ description: 'XP earned during the period', example: 340 })
  xpEarnedThisPeriod!: number;

  @ApiProperty({
    type: [QuizAttemptSummaryDto],
    description: 'Quiz attempt details within the period',
  })
  quizAttempts!: QuizAttemptSummaryDto[];

  // ── Computed insight ──────────────────────────────────────────────────────
  @ApiProperty({
    description: 'Human-readable highlight sentence generated by the system',
    example:
      'Bé đã hoàn thành 3 bài học và đạt điểm trung bình 78.5 trong tuần này 🎉',
  })
  highlightText!: string;
}
