/**
 * Base Create DTO - Minimal/empty base class
 * Use this when creating new entities
 *
 * Create DTOs should NOT include:
 * - id field (auto-generated)
 * - createdAt/updatedAt (auto-generated by database)
 * - isDeleted/deletedAt (auto-initialized to false/null)
 *
 * @example
 * export class CreateUserDto extends BaseCreateDto {
 *   @IsEmail()
 *   email!: string;
 *
 *   @IsString()
 *   @MinLength(8)
 *   password!: string;
 * }
 */
export class BaseCreateDto {}
